name: Automatically create pull requests
on: [create]
permissions: write-all
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4

      - name: Create pull request
        run: gh pr create --title "$(git branch --show-current)" --body "TBD"  --draft
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true

