---
name: Run tests on web/
on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2.4
          elixir-version: 1.18.2

      - name: Run tests
        working-directory: ./web/
        run: |
          mix deps.get
          mix test
